monitoramentoprecoproduto/accounts/urls.py
from django.urls import path

from .view import login_view, logout_view

app_name = "accounts"
urlpatterns = [
    path("login/", login_view.authenticate_user, name="login"),
    path("logout/", logout_view.logout_user, name="logout"),
]

monitoramentoprecoproduto/monitoramentoprecoproduto/urls.py
from accounts.view.home_redirect_view import home_redirect
from django.contrib import admin
from django.urls import include, path

from monitoramentoprecoproduto.admin import admin_site

urlpatterns = [
    path("admin/", admin_site.urls),
    path("", home_redirect),
    path("scraper/", include("scraper.urls", namespace="scraper")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

monitoramentoprecoproduto/scraper/urls.py
from django.contrib import admin
from django.urls import path

from .view import pagina_inicial_view, pagina_resultado_consulta_view

app_name = "scraper"
urlpatterns = [
    path("resultado_busca", pagina_resultado_consulta_view.pagina_resultado_view, name="resultado"),
    path("inicio", pagina_inicial_view.pagina_inicial_view, name="inicio"),
]

monitoramentoprecoproduto/accounts/models.py
from django.db import models

# Create your models here.

monitoramentoprecoproduto/scraper/models.py
from django.db import models


class Produto(models.Model):
    titulo = models.CharField("TÍTULO DO PRODUTO", max_length=255)
    valor = models.DecimalField("VALOR DO PRODUTO", max_digits=10, decimal_places=2)
    link = models.URLField("LINK PRODUTO", max_length=500, blank=True, null=True)
    imagem_url = models.URLField(max_length=500, null=True, blank=True)
    data = models.DateTimeField(auto_now_add=True)
    fonte = models.CharField(max_length=20, default="")

    def __str__(self):
        return f"{self.titulo} | {self.valor} | {self.link} | {self.data} | {self.imagem_url} | {self.fonte}"

monitoramentoprecoproduto/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def authenticate_user(request):
    context = {}

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("scraper:inicio"))
        else:
            context["message"] = "Usuário ou senha inválidos!."
            return render(request, "accounts/login.html", context)
    else:
        return render(request, "accounts/login.html", context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("accounts:login"))

monitoramentoprecoproduto/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'accounts/estilo_pagina_login.css' %}">
</head>
<body>
    <form action="{% url 'accounts:login' %}" method="POST">
        <h1 class="titulo_login">Login</h1>
        {% csrf_token %}
        {% if message %}
        <p>{{ message }}</p>
        {% endif %}
        <input type="text" name="username" id="username" placeholder="Usuário">
        <input type="password" name="password" id="password" placeholder="Senha">
        <input type="submit" value="Entrar">
    </form>
</body>
</html>

monitoramentoprecoproduto/scraper/templates/scraper/pagina_inicial.html
    {% load static %}
    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>PÁGINA INICIAL</title>
        <link rel="stylesheet" href="{% static 'scraper/estilo_pagina_inicial.css' %}">
    </head>
    <body>
        <header>
            <div class="container">
                <div class="titulo-container">
                    <h1 class="titulo">SEJA BEM-VINDO!</h1>
                </div>    
            </div>
        </header>   

        <main>

            <a class="botao_logout" href=" {% url 'accounts:logout' %} ">Sair</a>

            <div class="pesquisa-container">
                <form id="form-busca" action="{% url 'scraper:resultado' %}" method="get">
                    {% csrf_token %}
                    <input type="text" name="valor_buscado" placeholder="Digite o que deseja buscar..." required>
                    <input type="hidden" name="loja" id="input-loja">
                    <input type="hidden" name="categoria" id="input-categoria">
            
                    <button type="submit" name="botao_de_busca">Buscar</button>
            
                    <div class="logo_lojas_container">
                        <button type="button" class="quadrado_mercado_livre" onclick="selecionarLoja('mercadolivre')"></button>
                        <button type="button" class="quadrado_buscape" onclick="selecionarLoja('buscape')"></button>
                    </div>

                    <h2 class="paragrafo_mais_procurados">Mais Procurados</h2>
                    
                    <div class="categorias-populares-container">    
                        <button class="categoria-moda" onclick="selecionarCategoria('Moda')"></button>
                        <button class="categoria-eletronicos" onclick="selecionarCategoria('Eletrônicos')"></button>
                        <button class="categoria-casa" onclick="selecionarCategoria('Casa')"></button>
                        <button class="categoria-esportes" onclick="selecionarCategoria('Esportes')"></button>
                    </div>


                </form>
                
                <button type="button" class="botao_cancelar" onclick="cancelarBusca()"> CANCELAR</button>
                <div id="carregamento_busca" class="carregamento_busca" style="display: none;"></div>

            </div>
        </main>

        <script>
            const lojasSelecionadas = [];

            function selecionarLoja(nomeLoja) {
            const index = lojasSelecionadas.indexOf(nomeLoja);
            if (index > -1) {
                lojasSelecionadas.splice(index, 1); // Remove se já estava
            } else {
                lojasSelecionadas.push(nomeLoja); // Adiciona se não estava
            }
        
            document.getElementById('input-loja').value = lojasSelecionadas.join(",");
            console.log("Lojas selecionadas:", lojasSelecionadas);
            }

            let categoriaSelecionada = "";

            function selecionarCategoria(nomeCategoria){
                categoriaSelecionada = nomeCategoria;
            
                // Preenche o campo de busca com a categoria
                document.querySelector("input[name='valor_buscado']").value = nomeCategoria;
                document.getElementById('input-categoria').value = categoriaSelecionada;
            
                document.getElementById('carregamento_busca').style.display = 'block';
                document.getElementById('form-busca').submit();
            }
        
            document.addEventListener("DOMContentLoaded", function () {
            const form = document.querySelector("form");
            const buscarBtn = document.querySelector("button[name='botao_de_busca']");
            const carregamento = document.getElementById("carregamento_busca");
        
            carregamento.style.display = "none";
        
            window.addEventListener("pageshow", function (event) {
                if (event.persisted || performance.getEntriesByType("navigation")[0].type === "back_forward") {
                carregamento.style.display = "none";
                }
            });
        
            form.addEventListener("submit", function (e) {
                if (buscaCancelada) {
                    e.preventDefault(); // Impede o envio
                    buscaCancelada = false; // Reseta para o próximo uso
                    return;
                }
            
                const clickedButton = document.activeElement;
                if (clickedButton === buscarBtn) {
                    carregamento.style.display = "block";
                }
            });
        
            const logos = document.querySelectorAll('.quadrado_mercado_livre, .quadrado_buscape');
            logos.forEach(logo => {
                logo.addEventListener('click', () => {
                logo.classList.toggle('logo-ativa');
                });
            });
            });

            let buscaCancelada = false;

            function cancelarBusca() {
                // Seta flag de cancelamento
                buscaCancelada = true;
            
                // Limpa os campos do formulário
                document.querySelector("input[name='valor_buscado']").value = "";
                document.getElementById("input-loja").value = "";
                document.getElementById("input-categoria").value = "";  
                lojasSelecionadas.length = 0;
            
                // Esconde o carregamento
                document.getElementById('carregamento_busca').style.display = "none";
            
                // Remove destaque visual das lojas
                const logos = document.querySelectorAll('.logo-ativa');
                logos.forEach(logo => logo.classList.remove('logo-ativa'));
            }
        </script>
        

    </body>
    </html>

monitoramentoprecoproduto/scraper/templates/scraper/pagina_resultado_busca.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Produtos Encontrados</title>
  <link rel="stylesheet" href="{% static 'scraper/estilo_pagina_resultado_busca.css' %}">
</head>
<body>
  <div class="container">
    <div class="titulo-container">
      <h1 class="titulo">PRODUTOS ENCONTRADOS</h1>
    </div>

    <div class="carregando"></div>
    
    <a href="javascript:history.back()" class="seta-voltar">Voltar</a>

    <ul class="lista-produtos" style="display: none;">
      {% for produto in produtos %}
        <li class="produto">
          <img class="imagem-produto" src="{{ produto.imagem_url }}" alt="Imagem do Produto">
          <strong class="titulo-produto">{{ produto.titulo }}</strong>
          <p class="fonte-de-pesquisa">{{ produto.fonte }}</p>
          <div class="preco">Preço: {{ produto.valor }}</div>
          <a href="{{ produto.link }}" target="_blank">Ver Produto</a>
        </li>
      {% empty %}
        <li class="nenhum-produto">Nenhum produto encontrado.</li>
      {% endfor %}
    </ul>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const carregando = document.querySelector(".carregando");
      const listaProdutos = document.querySelector(".lista-produtos");

      carregando.style.display = "block";

      setTimeout(() => {
        carregando.style.display = "none";
        listaProdutos.style.display = "grid";
      }, 2000);
    });
  </script>
</body>
</html>